### ISSUE TITLE
Looks cool...

### ISSUE THREAD

**Issue by winkler1** [wmira/react-sidenav#1]
Online demo please? :) Would love to add to react.rocks.

rawgit can be a good way to host demos without too much work...

**Comment by wmira** [comment]
@winkler1 sure thing will get one up. cool site!

**Comment by wmira** [comment]
closing.. http://wmira.github.io/react-sidenav/

**Comment by winkler1** [comment]
Looks great, thanks!

**Comment by marcysutton** [comment]
Put that URL in your README!
