### ISSUE TITLE
CSS in picture on main page

### ISSUE THREAD

**Issue by nzayatz14** [wmira/react-sidenav#11]
Where is the CSS to make the sidenav look like the example picture you have on the main page?

By default it does not look like that. Mostly I need the indentations for the elements contained inside the dropdown menu.

**Comment by wmira** [comment]
Hi @nzayatz14 

This module has been deprecated and moved to reactor-ui projected. The documentation here should help you change it.

https://github.com/wmira/reactor-ui#sidenav
