### ISSUE TITLE
Uncaught TypeError: Cannot read property 'PropTypes' of undefined

### ISSUE THREAD

**Issue by SathishKannan** [wmira/react-sidenav#15]
Hi, I'm new to React, I downloaded react-sidenav and installed in my local machine.

Build is passing, but I'm seeing this error in my Chrome console,

![capture](https://cloud.githubusercontent.com/assets/6656974/23449894/580f69b0-fe7e-11e6-8a57-9962ed420a55.PNG)

Can you help me to fix this issue.

Thanks

**Comment by huumanoid** [comment]
React is declared as an [external](https://webpack.github.io/docs/library-and-externals.html) dependency.
That's why there is no React module in `bundle.js`.
For hotfix purposes, you may remove anything from `externals` in `webpack.config.js` file.

**Comment by wmira** [comment]
I have released 2.x version of sidenav and updated the main page with examples
