### ISSUE TITLE
Set route path as props on NavItem

### ISSUE THREAD

**Issue by kheide** [wmira/react-sidenav#29]
Now the withRR4 feature builds the path by looking at your nav item IDs. This is not a good solution as you're not always building your paths the same way as your nav tree. This should be able to be set by a prop on the `<Nav>` component

`<Nav id='dashboard' to='/app/dashboard'>`

**Comment by lynnchin** [comment]
Is this feature being implement yet?

**Comment by wmira** [comment]
@lynnchin this is already possible pay adding a payload to the nav and then setting to

<Nav payload={{to: '/somepath'}}/>
