### ISSUE TITLE
onItemSelection not invoked

### ISSUE THREAD

**Issue by dittmarconsulting** [wmira/react-sidenav#31]
"react": "^15.6.1",
"react-router": "4.1.1",
"react-sidenav": "^2.1.2"

const SideNav = withRR4()

```
     <SideNav
           highlightColor='rgb(255,255,255)'
           highlightBgColor='rgb(46,40,47)'
           hoverBgColor='rgb(118,118,118)'
           hoverColor='rgb(255,255,255)'
           onItemSelection={(id, parent) => console.log('clicked')}
           defaultSelected={locationName}>
           <Nav ...
```

**Comment by xCerNx** [comment]
Same here

**Comment by mreyes85** [comment]
same here, seems nav item onclick event is triggered but never reises to sidenav onItemselected

**Comment by wmira** [comment]
guys apologies on getting back. Was abit stuck on some real life stuff.

I just tried this with the playground and I onItemSelected is getting called can you see if you can re-create using this?

https://codesandbox.io/s/9j3yvqlppy

**Comment by mreyes85** [comment]
Hi,

Seems in your example it's working, but can't find the reason why mine don't:

<a href="https://codesandbox.io/s/xpv3rv0l0w">https://codesandbox.io/s/xpv3rv0l0w</a>

With RR4 I have automatic update to routes with the id (even if i set the onItemSelection) and the onItemSelection it's never triggered.

And I get always a warning for the withRR4

<code>
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.</code>

**Comment by nisar5071** [comment]
Hi,
  Try using like this
`onItemSelection={ this.onItemSelection } ` in render function

and bind it in constructor function like this
`this.onItemSelection = this.onItemSelection.bind(this);`

and you can see that function gets triggered 
```
onItemSelection(id, parent){
        console.log(parent)
 }
```

**Comment by wmira** [comment]
closing this now
