### ISSUE TITLE
Route path with RR4 not working properly

### ISSUE THREAD

**Issue by sapnalakhi** [wmira/react-sidenav#35]
Am using the Side nav with RR4 and have child under Nav as below

 <SideNav highlightColor='#E91E63' highlightBgColor='#00bcd4' defaultSelected='author'>
                <Nav id='author'>
                  <NavIcon><SvgIcon size={20} icon={ic_aspect_ratio} /></NavIcon>
                  <NavText> Author </NavText>
                  <Nav id="authorchild">
                    <NavIcon><SvgIcon size={20} icon={ic_data_usage} /></NavIcon>
                    <NavText> Hello </NavText>
                  </Nav>
                </Nav>

No when i go the child page i.e. authorchild, the url is displayed as 

http://localhost:3000/author/author/authorchild

Not sure why it is appending author again in the URL.

Appreciate your help!

**Comment by aswinr92** [comment]
Was anyone able to get this working?

**Comment by mbhaskar** [comment]
I have the same problem too. Is there some solution to this?

**Comment by wmira** [comment]
@mbhaskar i have publish a fix for this. You can try the playground rr4 and check

**Comment by mbhaskar** [comment]
Works great. Thanks @wmira

**Comment by wmira** [comment]
cool, closing this
