### ISSUE TITLE
Need help to embed react-sidenav into my Application

### ISSUE THREAD

**Issue by jainmanoj** [wmira/react-sidenav#38]
I am new to React so having real difficulty.
I am trying to embed react-sidenav playground into my application.
Using react-sidenav from --
https://github.com/wmira/react-sidenav

I am using its playground application to embed into following boiler plate
https://github.com/erikras/react-redux-universal-hot-example
I added a new Tab on the application  called  NavSideBarContainter 
and invoking NavSideBar component

I tried to convert playground a NavSideBar component

Now I created a NavSideBar Container and trying to render NavSideBar componet

import React, { Component } from 'react';
// import Helmet from 'react-helmet';
import { NavSideBar } from 'components';
// import {connect} from 'react-redux';

export default class NavSideBarContainter extends Component {
    static propTypes = {
      children: React.PropTypes.object
    };
    constructor(props) {
      super(props);
    }
    render() {
    //   const {children} = this.props;
      return (
            <div className="container">
                <NavSideBar />
            </div>
        );
    }
}

I am always getting this exception
SvgIcon.js:52 Uncaught (in promise) TypeError: Cannot read property 'children' of undefined
    at new SvgIcon (SvgIcon.js:52)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:148)
    at ReactCompositeComponentWrapper.wrapper [as mountComponent] (ReactPerf.js:66)
    at Object.mountComponent (ReactReconciler.js:37)
    at ReactDOMComponent.mountChildren (ReactMultiChild.js:241)
    at ReactDOMComponent._createContentMarkup (ReactDOMComponent.js:591)
    at ReactDOMComponent.mountComponent (ReactDOMComponent.js:479)
    at Object.mountComponent (ReactReconciler.js:37)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:225)
    at ReactCompositeComponentWrapper.wrapper [as mountComponent] (ReactPerf.js:66)

Not sure how to define properties children.
My thinking was to create Panel as Component and dock it with following application.

Please help.

**Comment by wmira** [comment]
@jainmanoj the SvgIcon from 'react-icons-kit' component needs an icon props. See example from https://github.com/wmira/react-sidenav/blob/master/playground/index.js#L9

**Comment by jainmanoj** [comment]
It is defined in NavSideBar component. It has all the props required to
render.

I am just trying to add this in container (boilerplate).

Not sure if I understood it correctly.

Need more help.

Thanks
Manoj

**Comment by wmira** [comment]
can you show more of the code pls.

**Comment by jainmanoj** [comment]
MANOJ>>>
I am using NAVSideBar class a component.
As such this component doens't expose any property

I am invoking NavSideBar into NodeSideBarContainer container with following
class

Route are defined it is trying to load NodeSideBarContainer class but
failing--
Not sure how to pass properties from container to component


import React, { Component } from 'react';
// import Helmet from 'react-helmet';
import { NavSideBar } from 'components';
// import {connect} from 'react-redux';

export default class NodeSideBarContainer extends Component {
static propTypes = {
icon: React.PropTypes.object
};
constructor(props) {
super(props);
}
render() {
// const {children} = this.props;
return (
<div className="container">
<NavSideBar />
</div>
);
}
}







// import { render } from 'react-dom';
import React, { Component, PropTypes } from 'react';
import { connect } from 'react-redux';
import { load } from 'redux/modules/navsidebar';
import { bindActionCreators } from 'redux';

import styled from 'styled-components';

import SideNav, { Nav, NavIcon, NavText } from 'react-sidenav';
import SvgIcon from 'react-icons-kit';
import { ICAspectRatio } from 'react-icons-kit/md/ic_aspect_ratio';
import { ICBusiness } from 'react-icons-kit/md/ic_business';
import { ICBusinessCenter } from 'react-icons-kit/md/ic_business_center';
import { ICFormatListBulleted } from
'react-icons-kit/md/ic_format_list_bulleted';
import { ICPeople } from 'react-icons-kit/md/ic_people';
import { ICShoppingCart } from 'react-icons-kit/md/ic_shopping_cart';

const Icon20 = props => <SvgIcon size={props.size || 20} icon={props.icon}
/>;

Icon20.propTypes = {
size: React.PropTypes.string,
icon: React.PropTypes.object
};

const BaseContainer = props =>
<div
style={{
display: 'inline-block',
paddingTop: 16,
paddingBottom: 16,
fontFamily: 'Roboto',
width: 240,
...props.style
}}
>
{props.children}
</div>;

BaseContainer.propTypes = {
style: React.PropTypes.object,
size: React.PropTypes.string,
icon: React.PropTypes.string,
children: React.PropTypes.object
};


const Title = styled.div`
padding: 12px;
`;

const Separator = styled.div`
padding-right: 12px;
`;
const SeparatorTitleContainer = styled.div`
font-size: 14px;
color: #AAA;
margin: 10px 12px;
padding: 4px 12px 2px;
`;
const SeparatorTitle = props => {
return (
<SeparatorTitleContainer>
{props.children}
<hr style={{ border: 0, borderTop: '1px solid #E5E5E5' }} />
</SeparatorTitleContainer>
);
};

SeparatorTitle.propTypes = {
children: React.PropTypes.object
};
const BasicSideNav = () =>
<SideNav highlightBgColor="#00bcd4" defaultSelected="sales">
<Title> Basic SideNav </Title>
<Nav id="dashboard">
<NavIcon><Icon20 icon={ICAspectRatio} /></NavIcon>
<NavText> Dashboard </NavText>
</Nav>
<Nav id="sales">
<NavIcon><Icon20 icon={ICBusiness} /></NavIcon><NavText> Sales </NavText>
</Nav>
<Nav id="products">
<NavIcon><Icon20 icon={ICBusinessCenter} /></NavIcon>
<NavText> Products </NavText>
</Nav>
<Nav id="customers">
<NavIcon><Icon20 icon={ICPeople} /></NavIcon>
<NavText> Customers </NavText>
<Nav id="dashboard2">
<NavIcon><Icon20 size={16} icon={ICAspectRatio} /></NavIcon>
<NavText> Search </NavText>
</Nav>
<Nav id="sales2">
<NavIcon><Icon20 size={16} icon={ICBusiness} /></NavIcon>
<NavText> Promote </NavText>
</Nav>
<Nav id="products2">
<NavIcon><Icon20 size={16} icon={ICBusinessCenter} /></NavIcon>
<NavText> Social Media </NavText>
</Nav>
</Nav>
<Nav id="orders">
<NavIcon><Icon20 icon={ICFormatListBulleted} /></NavIcon>
<NavText> Orders </NavText>
</Nav>
</SideNav>;

const NavMain = {
dashboard: { title: 'Dashboard', icon: ICAspectRatio },
products: { title: 'Products', icon: ICBusinessCenter },
orders: { title: 'Orders', icon: ICFormatListBulleted }
};

const BasicSideNavLite = () =>
<SideNav
highlightBgColor="#eee"
defaultSelected="products"
highlightColor="#E91E63"
>
<SeparatorTitle><div>Main</div></SeparatorTitle>
{Object.keys(NavMain).map(key => {
// dynamically created the navs
return (
<Nav key={key} id={key}>
<NavIcon><Icon20 icon={NavMain[key].icon} /></NavIcon>
<NavText> {NavMain[key].title} </NavText>
</Nav>
);
})}
<SeparatorTitle>
<div> Customers and Sales</div>
</SeparatorTitle>
<Nav id="customers">
<NavIcon><Icon20 icon={ICPeople} /></NavIcon>
<NavText> Customers </NavText>
<Nav id="dashboard2">
<NavIcon><Icon20 size={16} icon={ICAspectRatio} /></NavIcon>
<NavText> Search </NavText>
</Nav>
<Nav id="sales2">
<NavIcon><Icon20 size={16} icon={ICBusiness} /></NavIcon>
<NavText> Promote </NavText>
</Nav>
<Nav id="products2">
<NavIcon><Icon20 size={16} icon={ICBusinessCenter} /></NavIcon>
<NavText> Social Media </NavText>
</Nav>
</Nav>
<Nav id="sales">
<NavIcon><Icon20 icon={ICBusiness} /></NavIcon><NavText> Sales </NavText>
</Nav>
</SideNav>;

const SideNavWithAlerts = () =>
<SideNav
hoverBgColor="#232a2f"
hoverColor="red"
highlightBgColor="#00acac"
defaultSelected="products"
highlightColor="#FFF"
>
<div />
<Nav id="dashboard">
<NavIcon><Icon20 icon={ICAspectRatio} /></NavIcon>
<NavText> Dashboard </NavText>
</Nav>

<Nav id="products">
<NavIcon><Icon20 icon={ICBusinessCenter} /></NavIcon>
<NavText> Products </NavText>
</Nav>
<Nav id="orders">
<NavIcon><Icon20 icon={ICFormatListBulleted} /></NavIcon>
<NavText>
{' '}<span style={{ paddingRight: 6 }}>Orders</span>{' '}
<span
style={{
textAlign: 'center',
lineHeight: '16px',
height: 16,
width: 16,
margin: '0 auto',
borderRadius: '50%',
fontSize: 9,
display: 'inline-block',
color: '#FFF',
background: '#ff5b57'
}}
>
10
</span>
</NavText>
</Nav>

<Nav id="customers">
<NavIcon><Icon20 icon={ICPeople} /></NavIcon>
<NavText> Customers </NavText>
<Nav id="dashboard2">
<NavIcon><Icon20 size={16} icon={ICAspectRatio} /></NavIcon>
<NavText> Search </NavText>
</Nav>
<Nav
id="sales2"
onNavClick={() => {
console.log('Promote clicked!', arguments);
}}
>
<NavIcon><Icon20 size={16} icon={ICBusiness} /></NavIcon>
<NavText> Promote </NavText>
</Nav>
<Nav id="products2">
<NavIcon><Icon20 size={16} icon={ICBusinessCenter} /></NavIcon>
<NavText> Social Media </NavText>
</Nav>
</Nav>
<Nav
id="sales"
onNavClick={() => {
console.log('Sales clicked!', arguments);
}}
>
<NavIcon><Icon20 icon={ICBusiness} /></NavIcon><NavText> Sales </NavText>
</Nav>
<Nav id="deliveries">
<NavIcon><Icon20 icon={ICShoppingCart} /></NavIcon>
<NavText> Deliveries </NavText>
</Nav>
</SideNav>;

const ControlledNav = () =>
<SideNav
hoverBgColor="#232a2f"
hoverColor="red"
highlightBgColor="#00acac"
selected="customers/sales2"
highlightColor="#FFF"
>
<div />
<Nav id="dashboard">
<NavIcon><Icon20 icon={ICAspectRatio} /></NavIcon>
<NavText> Dashboard </NavText>
</Nav>

<Nav id="products">
<NavIcon><Icon20 icon={ICBusinessCenter} /></NavIcon>
<NavText> Products </NavText>
</Nav>
<Nav id="orders">
<NavIcon><Icon20 icon={ICFormatListBulleted} /></NavIcon>
<NavText>
{' '}<span style={{ paddingRight: 6 }}>Orders</span>{' '}
<span
style={{
textAlign: 'center',
lineHeight: '16px',
height: 16,
width: 16,
margin: '0 auto',
borderRadius: '50%',
fontSize: 9,
display: 'inline-block',
color: '#FFF',
background: '#ff5b57'
}}
>
10
</span>
</NavText>
</Nav>

<Nav id="customers" expanded>
<NavIcon><Icon20 icon={ICPeople} /></NavIcon>
<NavText> Customers </NavText>
<Nav id="dashboard2">
<NavIcon><Icon20 size={16} icon={ICAspectRatio} /></NavIcon>
<NavText> Search </NavText>
</Nav>
<Nav
id="sales2"
onNavClick={() => {
console.log('Promote clicked!', arguments);
}}
>
<NavIcon><Icon20 size={16} icon={ICBusiness} /></NavIcon>
<NavText> Promote </NavText>
</Nav>
<Nav id="products2">
<NavIcon><Icon20 size={16} icon={ICBusinessCenter} /></NavIcon>
<NavText> Social Media </NavText>
</Nav>
</Nav>
<Nav
id="sales"
onNavClick={() => {
console.log('Sales clicked!', arguments);
}}
>
<NavIcon><Icon20 icon={ICBusiness} /></NavIcon><NavText> Sales </NavText>
</Nav>
<Nav id="deliveries">
<NavIcon><Icon20 icon={ICShoppingCart} /></NavIcon>
<NavText> Deliveries </NavText>
</Nav>
</SideNav>;

@connect(
state => ({ icon: state.icon }),
dispatch => bindActionCreators({ load }, dispatch))
export default class NavSideBar extends React.Component {
static propTypes = {
icon: PropTypes.object
}
render() {
return (
<div style={{ display: 'flex' }}>
<BaseContainer style={{ background: '#2c3e50', color: '#FFF' }}>
<BasicSideNav />
</BaseContainer>
{ /* <Separator />
<BaseContainer
style={{
background: '#FFF',
color: '#444',
boxShadow: '0 3px 6px rgba(0,0,0,0.16), 0 3px 6px rgba(0,0,0,0.23)'
}}
>
<BasicSideNavLite />
</BaseContainer>
<Separator />
<BaseContainer
style={{
fontSize: 12,
background: '#2d353c',
color: '#a8acb1',
paddingTop: 0
}}
>
<div style={{ display: 'flex', padding: 16, background: '#1a2229' }}>
<div style={{ width: 40, height: 40 }}>
<img
src="https://e27.co/img/profiles/15483/profile_pic.png"
style={{ borderRadius: '30px', width: 40, height: 40 }}
/>
</div>
<div style={{ paddingLeft: 6, paddingTop: 6 }}>
<div style={{ fontSize: 12, color: '#E5E5E5' }}>
{' '}Warren Mira{' '}
</div>
<div style={{ fontSize: 11 }}> Ninja Developer </div>
</div>
</div>
<SideNavWithAlerts />
</BaseContainer>
<Separator />
<BaseContainer
style={{
background: '#FFF',
color: '#444',
boxShadow: '0 3px 6px rgba(0,0,0,0.16), 0 3px 6px rgba(0,0,0,0.23)'
}}
>
<ControlledNav />
</BaseContainer>
<Separator /> */}
</div>
);
}
}

// render(<NavSideBar />, document.getElementById('container'));

**Comment by wmira** [comment]
@jainmanoj you used connect from react-redux and you are getting the icon attribute from the redux state. are you sure it has the icon field?

**Comment by jainmanoj** [comment]
No this icon is not getting filled.
First I  was trying without redux. As I was thinking there is no property
to be exchanges as NavSideBar is complete component.
But that also didn't work

**Comment by jainmanoj** [comment]
Is there any example of using react-sidenav with redux?

**Comment by wmira** [comment]
@jainmanoj you can just pass the selectedPath directly from your store
