### ISSUE TITLE
Nested items (submenus)?

### ISSUE THREAD

**Issue by OKNoah** [wmira/react-sidenav#5]
The screenshot shows submenus, i.e. items nested under other items. Where are there instructions or examples of this?

Thank you.

**Comment by OKNoah** [comment]
Found it here

        {id: 'inventory', title: 'Inventory',
            'sub-menu': [
                { id: 'levels', title: 'Product Levels', 'icon-cls': 'fa fa-list'},
                { id: 'levels', title: 'Sales Report', 'icon-cls': 'fa fa-area-chart'},
            ]
        },

I may fork and add this to the `readme`

**Comment by baronnoraz** [comment]
@OKNoah - Is this working?  I'm using the component in JSX, but I keep getting "Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined" @react-sidenav.js:222 

```javascript
React.Children.map(this.props.children, function(child)  {
```
using the following config

```javascript
{key: 'parentMenu', title: 'Parent Menu','iconClassName': 'fa fa-exchange',
   subMenu: [
      {key: 'childMenu', title: 'Child Menu', 'iconClassName': 'fa fa-exchange'}
    ]
},
```
My menu works fine until I try to include the subMenu.  Any thoughts?  I'd love to know for sure if someone else has sub menus working. THANKS!

**Comment by baronnoraz** [comment]
Is there an example of how to configure submenus manually without supplying the navigation attribute?

```javascript
<SideNav.Menu className={"sidenav"} itemHeight="32px">
    <SideNav.MenuItem itemKey={"test-parent"}>
        <SideNav.IRightItem className={"fa fa-truck"}>
            Test Parent
        </SideNav.IRightItem>
        <SideNav.Menu className={"sidenav-submenu"} itemHeight="32px">
            <SideNav.MenuItem className={"sidenav-submenu-item"} itemKey={"test-child"}>
                <SideNav.PlainLink>TRUCK</SideNav.PlainLink>
            </SideNav.MenuItem>
        </SideNav.Menu>
    </SideNav.MenuItem>
</SideNav.Menu>
```

I've tried many variations on this theme, and the best I could do was to get the submenu items to render on top of the parent items.

**Comment by wmira** [comment]
This component has been updated. I'm adding support for custom renders. Closing this issue now and I have added sub-menu on the README
