### ISSUE TITLE
defaultSelected with sub menu

### ISSUE THREAD

**Issue by jchambers-ln** [wmira/react-sidenav#50]
Given
```
import SideNav, { Nav, NavIcon, NavText } from 'react-sidenav';
...

<SideNav defaultSelected={'mySubMenu'} >
  <Nav id='config'>
    <NavText>Configuration</NavText>
    <Nav id='mySubMenu'>
      <NavText><RouterRingLink to="/admin/mySubAdmin"> My Sub Menu</RouterRingLink></NavText>
    </Nav>
  </Nav>
</SideNav>)

```

The "mySubMenu" is not selected-- how does one get the sub menu to expand and select the right node?

I've tried 'config/mySubMenu' as the value to defaultSelected and that didn't seem to work.

**Comment by wmira** [comment]
@jchambers-ln you would need to use a path to have a subMenu selected 
e.g.
defaultSelected={'config$|$mySubmenu'}

Please use the latest react-sidenav for this feature to work
