### ISSUE TITLE
Missing `withRR4` on latest version

### ISSUE THREAD

**Issue by George-Aidonidis** [wmira/react-sidenav#65]
Hello, 

I am not sure if there is some other way to use the integration of React Router but following the readme did not work :upside_down_face: 

### What's happening
The `withRR4` hoc is missing on latest release

### Steps to reproduce

```js
import { withRR4 } from "react-sidenav";

const SideNav = withRR4();

// error --> (0 , _reactSidenav.withRR4) is not a function
```

### Sandbox where the issue is presented
Here is a forked version from the readme (original [version](https://codesandbox.io/s/q9851xoymj))
Forked version [here](https://codesandbox.io/s/n9wrk4261j)

The readme's version seems to be using `3.0.9`

### Version
* React-sidenav: 3.1.1

**Comment by wmira** [comment]
Hi George,

I intentionally removed it from the main export as it is causing react-router to be automatically required even though it is a peer dependency.

You should be able to use it via
import { withRR4 } from "react-sidenav/withRR4";

**Comment by George-Aidonidis** [comment]
Hi @wmira

Ah, it makes sense then.
Thanks for your time
