### ISSUE TITLE
‘withRR4’ not working on latest version (3.1.3)

### ISSUE THREAD

**Issue by RunnerTx** [wmira/react-sidenav#66]
When I got the latest version (3.1.3) of the control, the React Router functionality no longer seems to work.
<br />I forked the original version from the readme [(original version)](https://codesandbox.io/s/q9851xoymj)
<br />Updated the react-sidenav dependency to 3.1.3 and changed the RR4 import in the AppNavigation.js file to 

> import { withRR4 } from "react-sidenav/withRR4"; 

[forked version](https://codesandbox.io/s/j73q94qvm5) like the previous [bug](https://github.com/wmira/react-sidenav/issues/65) mentioned.

<br />There was also a bug in the [(original sandbox version)](https://codesandbox.io/s/q9851xoymj).  If you click on the "Home" button (the route that has an exact path), the body section goes blank.

**Comment by wmira** [comment]
Hi @RunnerTx add a basePath on the main SideNav or pass a payload with { to: 'path } on each navigation.

Here is the updated forked version: https://codesandbox.io/s/kwyznv18yr

**Comment by RunnerTx** [comment]
Hello @wmira - thanks for the response.  Adding the basePath does resolve the first issue, but could you clarify a bit more on the second option:  

> pass a payload with { to: 'path }

Lastly the original bug I mentioned in is still there:

> There was also a bug in the (original sandbox version). If you click on the "Home" button (the route that has an exact path), the body section goes blank.

Should I close this bug and open a new one with that issue specifically?

**Comment by wmira** [comment]
@RunnerTx  no need to create a new issue. Will fix it using this ticket. You can do something like:

```
SideNav>
                <Nav id="products" payload={{ to: `/somepath/products` }}>
                    Products
                </Nav>
                <Nav id="orders" payload={{ to: `/somepath/orders` }}>
                    Orders
                </Nav>
                <Nav id="transactions" payload={{ to: `/somepath/transactions` }}>
                    Transactions
                </Nav>
            </SideNav>
```

will release something this weekend and updating the docs and sample.

@RunnerTx  thanks for reporting again.

**Comment by RunnerTx** [comment]
@wmira - i tested the fix and everything is working as expected.  

Thanks for the quick turnaround on resolving this issue.
