### ISSUE TITLE
@typescript/react-sidenav using with typescript need help to embed it in my application

### ISSUE THREAD

**Issue by pranayb703** [wmira/react-sidenav#67]
Hi wmira ,

I am using typescript and trying to import react-sidenav in my application and its giving me error of cannot find module. I have added it in package.json and ran npm install --save too. Can you help me how can we use this in typescript.

Great job.  Thanks for the help!

**Comment by wmira** [comment]
Hi this project is written in typescript so you should have the typings. Just do npm install --save react-sidenav. The playground folder has example of using it via typescript.

What specific errors are you getting?

**Comment by pranayb703** [comment]
Hi I added the react-sidenav in package.json file and did npm install --save. It says react-sidenav not reacognized . Also I am not able to add @typescript/react-sidenav in package.json. New here so not much aware how to use this library in react app. Thanks for the help and quick response ! @wmira
