### ISSUE TITLE
Warnings in console

### ISSUE THREAD

**Issue by Nijooke** [wmira/react-sidenav#68]
Hi,

I have a lot of warnings in my console and I don't know why

Here is a screenshot

![capture](https://user-images.githubusercontent.com/16818361/52068516-17167c00-257d-11e9-9f5c-e0a5f733e305.PNG)

I'm using the lastest version of react-sidenav (3.1.5), and I already tried to reinstall node_modules

Do you have any how to fix the issue ?

Thank you in advance for your answers !

**Comment by wmira** [comment]
@Nijooke this seems to have something to do with the source map. Will do a release that will exclude it. In the meantime you can use exclude on your source-map-loader setting. Do you have your own webpack config ?

**Comment by Nijooke** [comment]
@wmira Thank you for your very quick answer and for your work on this library !
Indeed, I use my own webpack config.
I added as you suggested "exclude" to source-map-loader and the warnings have disappeared !
Thanks again!
