### ISSUE TITLE
Remove the mixin and add an Item component

### ISSUE THREAD

**Issue by wmira** [wmira/react-sidenav#7]
Add a new Item component to be used to render nav items.

**Comment by AtNovember** [comment]
i`ve  made it like this 


const SideNavComponent = React.createClass({

        getInitialState() {
            this.setState({selected: 'dashboard'});
        },
        onSelection(selection) {
            this.setState({selected: selection.id});
        },
        render() {
            return <SideNav selected={this.state.selected} navs={navi} onSelection={this.onSelection} />
        }
    });

----------

try to use    this.setState({selected: 'dashboard'}); 
instead of   return { selected: 'dashboard' };  
at the getInitialState() section
