### ISSUE TITLE
[typescript] withRR4 type is not undefined

### ISSUE THREAD

**Issue by jungpaeng** [wmira/react-sidenav#72]
![image](https://user-images.githubusercontent.com/26024412/54535672-5df7ee00-49d2-11e9-8b4e-4f161b67f91c.png)

**Comment by wmira** [comment]
Hi @jungpaeng withRr4 was removed from index to prevent error of neededing react router as a dep as it is a peer dependency. 

https://github.com/wmira/react-sidenav/issues/65

**Comment by wmira** [comment]
Please see the issue linked above

**Comment by jungpaeng** [comment]
> Please see the issue linked above

I really want to thank you for your help!
