### ISSUE TITLE
expandOnHover does not work with sub menus in non-collapsed state

### ISSUE THREAD

**Issue by LoganArnett** [wmira/react-sidenav#76]
the expandOnHover prop is great as a concept but it currently does not support the hovered state of the sub menu items in keeping the parent open. Every time I hover the sub menu is displayed but as soon as I try to move to one of them and lose the parent target then they hide before I can click any of them.

Example:
![ss](http://cloud.loganarnett.com/bf6984c8d340/Screen%252520Recording%2525202019-05-20%252520at%25252011.26%252520AM.gif)

**Comment by wmira** [comment]
@LoganArnett thanks for reporting will get this feature fixed up on latest version.

**Comment by wmira** [comment]
@LoganArnett is this on latest 4.x version? If so 4.0.3 has the fix
