### ISSUE TITLE
Updated README / List of SideNav properties

### ISSUE THREAD

**Issue by michaelsklepowich** [wmira/react-sidenav#80]
Hello, I want to use this module in my project but I can't find a comprehensive list of the properties available to the SideNav component.

The list titled [SideNav Properties](https://github.com/wmira/react-sidenav#sidenav-properties) only has `onSelection` and `defaultSelectedPath`

But this [codepen example](https://codesandbox.io/s/p9kly6kox0) has the `expandOnHover` property from this issue [here](https://github.com/wmira/react-sidenav/issues/47).

Is there a full list of properties somewhere else, thanks.

**Comment by wmira** [comment]
Hi @michaelsklepowich the link you gave was for the previous version of react-sidenav. The latest version was changed such that users have more control of the rendering and provides state of nav items via context and at the same time remove peerDeps from styled components. Please see the example section here:

https://react-sidenav.now.sh/

**Comment by wmira** [comment]
@michaelsklepowich  closing this issue now.

**Comment by michaelsklepowich** [comment]
@wmira Thank you for clarifying. Perhaps you could add version number to the titles of your codepen examples to prevent confusion.
