### ISSUE TITLE
How would i alter the style?

### ISSUE THREAD

**Issue by DrNotThatEvil** [wmira/react-sidenav#9]
This might be a really dumb or nooby question.
But i would like to alter the style of the sidebar (darker color for expanded items)

How could i do something like this ? 
Could it be possible to supply a custom class in the configuraton object ?

Thanks in advance for your time.

**Comment by yanivkalfa** [comment]
@DrNotThatEvil You can try https://www.npmjs.com/package/react-nav-bar it might be what you're looking for you can customize alot there.

**Comment by DrNotThatEvil** [comment]
Thanks. I already build a own slightly more basic sidebar based on another plugin.
Sorry i did not keep this issue up to date.
